package com.myaccounts.app.util

import android.content.Context
import android.net.Uri
import android.util.Base64
import com.myaccounts.app.data.custody.CustodyAttachmentStorage
import com.myaccounts.app.data.custody.CustodyAttachmentStore
import com.myaccounts.app.data.local.AppDatabase
import java.io.ByteArrayOutputStream
import java.io.File
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream

object CustodyBackupManager {
    const val MIME_TYPE = "application/vnd.myaccounts.custody-backup+zip"
    const val SUGGESTED_FILE_NAME = "MyAccounts_Custodies_Backup.custody"
    private const val WORKBOOK = "custody.xlsx"
    private const val MANIFEST = "attachments.tsv"
    private const val ATTACHMENTS = "attachments/"
    data class Summary(val custodies:Int,val people:Int,val accounts:Int,val transactions:Int,val attachments:Int)
    suspend fun createBackup(context:Context,uri:Uri):Result<Summary> = runCatching { val db=AppDatabase.getInstance(context); val dao=db.custodyDao(); val custodies=dao.getAllCustodies(false); val people=custodies.flatMap{dao.getAllPersons(it.id)}; val accounts=custodies.flatMap{dao.getAllAccounts(it.id)}; val transactions=custodies.flatMap{dao.getAllTransactions(it.id,false)}; val attachments=transactions.flatMap{CustodyAttachmentStore(context).list(it.id)}; val workbookFile=File(context.cacheDir,"custody-backup-${System.nanoTime()}.xlsx"); try { CustodyExcelDataManager.exportActive(context,Uri.fromFile(workbookFile)).getOrThrow(); context.contentResolver.openOutputStream(uri)?.use{output->ZipOutputStream(output.buffered()).use{zip->zip.putNextEntry(ZipEntry(WORKBOOK));workbookFile.inputStream().use{it.copyTo(zip)};zip.closeEntry();val manifest=buildString{attachments.forEachIndexed{index,a->val tx=transactions.firstOrNull{it.id==a.transactionId}?:return@forEachIndexed;append(index).append('\t');append(Base64.encodeToString(tx.externalId.toByteArray(Charsets.UTF_8),Base64.NO_WRAP)).append('\t');append(Base64.encodeToString(a.fileName.toByteArray(Charsets.UTF_8),Base64.NO_WRAP)).append('\t');append(Base64.encodeToString(a.mimeType.toByteArray(Charsets.UTF_8),Base64.NO_WRAP)).append('\n');zip.putNextEntry(ZipEntry("$ATTACHMENTS$index.bin"));val file=CustodyAttachmentStorage.fileFor(context,a);require(file.isFile){"مرفق العهدة مفقود: ${a.fileName}"};file.inputStream().use{it.copyTo(zip)};zip.closeEntry()}};zip.putNextEntry(ZipEntry(MANIFEST));zip.write(manifest.toByteArray(Charsets.UTF_8));zip.closeEntry()}}?:error("تعذر فتح ملف النسخة الاحتياطية للكتابة.") } finally { workbookFile.delete() }; Summary(custodies.size,people.size,accounts.size,transactions.size,attachments.size) }
    suspend fun restoreBackup(context:Context,uri:Uri):Result<Summary> = runCatching { val entries=readZip(context,uri); val workbook=entries[WORKBOOK]?:error("نسخة العهد الاحتياطية غير صالحة: ملف البيانات مفقود."); val db=AppDatabase.getInstance(context); val temp=File(context.cacheDir,"custody-restore-${System.nanoTime()}.xlsx");temp.outputStream().use{it.write(workbook)};try{val imported=CustodyExcelDataManager.import(context,Uri.fromFile(temp)).getOrThrow();val manifest=entries[MANIFEST]?.toString(Charsets.UTF_8).orEmpty();var restoredAttachments=0;if(manifest.isNotBlank()){val dao=db.custodyDao();manifest.lineSequence().filter{it.isNotBlank()}.forEach{line->val p=line.split('\t');if(p.size!=4)return@forEach;val txExternalId=String(Base64.decode(p[1],Base64.NO_WRAP),Charsets.UTF_8);val fileName=String(Base64.decode(p[2],Base64.NO_WRAP),Charsets.UTF_8);val mimeType=String(Base64.decode(p[3],Base64.NO_WRAP),Charsets.UTF_8);val tx=dao.getTransactionByExternalId(txExternalId)?:return@forEach;val bytes=entries["$ATTACHMENTS${p[0]}.bin"]?:return@forEach;val tempAttachment=writeTemp(context,"attachment",bytes);try{val saved=CustodyAttachmentStorage.saveAttachments(context,tx.id,listOf(CustodyAttachmentStorage.Selected(Uri.fromFile(tempAttachment),fileName,mimeType)));saved.forEach{a->db.openHelper.writableDatabase.execSQL("INSERT INTO custody_transaction_attachments (transactionId,fileName,mimeType,relativePath,sizeBytes,createdAt) VALUES (?,?,?,?,?,?)",arrayOf(a.transactionId,a.fileName,a.mimeType,a.relativePath,a.sizeBytes,a.createdAt))};restoredAttachments+=saved.size}finally{tempAttachment.delete()}}};Summary(imported.custodiesAdded,imported.peopleAdded,imported.accountsAdded,imported.transactionsAdded,restoredAttachments)}finally{temp.delete()} }
    private fun writeTemp(context:Context,prefix:String,bytes:ByteArray):File{val file=File(context.cacheDir,"$prefix-${System.nanoTime()}.bin");file.outputStream().use{it.write(bytes)};return file}
    private fun readZip(context:Context,uri:Uri):Map<String,ByteArray>{val input=context.contentResolver.openInputStream(uri)?:error("تعذر فتح ملف نسخة العهد الاحتياطية.");val result=mutableMapOf<String,ByteArray>();ZipInputStream(input.buffered()).use{zip->while(true){val entry=zip.nextEntry?:break;if(entry.isDirectory)continue;val out=ByteArrayOutputStream();zip.copyTo(out);result[entry.name]=out.toByteArray()}};return result}
}