package com.myaccounts.app.util

import android.content.ContentValues
import android.content.Context
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import com.myaccounts.app.data.reports.CurrencyReportPersonRow
import com.myaccounts.app.data.reports.CurrencyReportSummary
import com.myaccounts.app.data.reports.GeneralReportTransactionRow
import com.myaccounts.app.data.reports.PersonCurrencySummaryRow
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.math.BigDecimal
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

object GeneralReportsExcelExporter {
    fun exportPeopleReport(context: Context,currency:String,summary:CurrencyReportSummary,people:List<CurrencyReportPersonRow>,start:Long?,end:Long?):Result<String> = export(context,"تقرير الأشخاص",currency,peopleSheet(summary,people,start,end))
    fun exportDetailedReport(context: Context,currency:String,transactions:List<GeneralReportTransactionRow>,start:Long?,end:Long?):Result<String> = export(context,"التقرير التفصيلي",currency,detailedSheet(currency,transactions,start,end))
    fun exportSummaryReport(context: Context,currency:String,rows:List<PersonCurrencySummaryRow>,start:Long?,end:Long?):Result<String> = export(context,"ملخص تقرير الأشخاص",currency,summarySheet(currency,rows,start,end))
    private fun export(context:Context,title:String,currency:String,sheet:String):Result<String> = try { val fileName="MyAccounts_${safe(title)}_${currency}_${SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(Date())}.xlsx";if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.Q){val values=ContentValues().apply{put(MediaStore.Downloads.DISPLAY_NAME,fileName);put(MediaStore.Downloads.MIME_TYPE,XLSX_MIME_TYPE);put(MediaStore.Downloads.RELATIVE_PATH,"${Environment.DIRECTORY_DOWNLOADS}/MyAccounts")};val resolver=context.contentResolver;val uri=resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,values)?:throw IllegalStateException("تعذر إنشاء ملف Excel.");try{resolver.openOutputStream(uri).use{out->if(out==null)throw IllegalStateException("تعذر فتح ملف Excel.");writeWorkbook(out,sheet)}}catch(e:Exception){resolver.delete(uri,null,null);throw e};Result.success("تم حفظ التقرير في مجلد التنزيلات/MyAccounts")}else{val dir=File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS),"MyAccounts");if(!dir.exists()&&!dir.mkdirs())throw IllegalStateException("تعذر إنشاء مجلد التقرير.");val file=File(dir,fileName);FileOutputStream(file).use{writeWorkbook(it,sheet)};Result.success(file.absolutePath)}}catch(e:Exception){Result.failure(e)}
    private fun writeWorkbook(out:OutputStream,sheet:String){ZipOutputStream(out).use{z->entry(z,"[Content_Types].xml",contentTypes());entry(z,"_rels/.rels",rootRels());entry(z,"xl/workbook.xml",workbook());entry(z,"xl/_rels/workbook.xml.rels",workbookRels());entry(z,"xl/styles.xml",styles());entry(z,"xl/worksheets/sheet1.xml",sheet)}}
    private fun entry(z:ZipOutputStream,p:String,v:String){z.putNextEntry(ZipEntry(p));z.write(v.toByteArray(Charsets.UTF_8));z.closeEntry()}
    private fun contentTypes()="""<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>"""
    private fun rootRels()="""<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>"""
    private fun workbook()="""<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="التقرير" sheetId="1" r:id="rId1"/></sheets></workbook>"""
    private fun workbookRels()="""<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>"""
    private fun styles()="""<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="+0.00;-0.00;0.00"/></numFmts><fonts count="5"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="14"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font><font><color rgb="FF00804A"/><b/><sz val="11"/><name val="Arial"/></font><font><color rgb="FFC02323"/><b/><sz val="11"/><name val="Arial"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEAF3EE"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFCEBEC"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style="thin"/><right style="thin"/><top style="thin"/><bottom style="thin"/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="8"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="3" fillId="2" borderId="1" xfId="0"/><xf numFmtId="0" fontId="4" fillId="3" borderId="1" xfId="0"/><xf numFmtId="164" fontId="3" fillId="2" borderId="1" xfId="0"/><xf numFmtId="164" fontId="4" fillId="3" borderId="1" xfId="0"/><xf numFmtId="164" fontId="0" fillId="0" borderId="1" xfId="0"/></cellXfs></styleSheet>"""
    private fun peopleSheet(s:CurrencyReportSummary,p:List<CurrencyReportPersonRow>,start:Long?,end:Long?):String{val rows=mutableListOf<String>();var n=1;rows+=row(n++,listOf(cell("تقرير الأشخاص",1)));rows+=row(n++,listOf(cell("العملة: ${currencyName(s.currencyCode)}",2),cell("الفترة: ${range(start,end)}",2),cell("إصدار: ${date(System.currentTimeMillis())}",2)));rows+=row(n++,listOf(cell("ملخص الحساب",2)));rows+=row(n++,listOf(cell("عليه",3),number(s.totalReceivableMinor,5),cell("له",4),number(-s.totalPayableMinor,6),cell("الرصيد",2),number(s.balanceMinor,7),cell("العمليات",2),integer(s.transactionCount.toLong(),2)));val h=n;rows+=row(n++,listOf(cell("الشخص",2),cell("العملة",2),cell("عليه",3),cell("له",4),cell("الرصيد",2)));p.forEach{x->rows+=row(n++,listOf(cell(x.personName),cell(currencyName(s.currencyCode)),number(x.totalReceivableMinor,5),number(-x.totalPayableMinor,6),number(x.balanceMinor,7)))};if(p.isEmpty())rows+=row(n++,listOf(cell("لا توجد بيانات.")));return sheet(rows,"A$h:E${n-1}","32,18,18,18,20")}
    private fun detailedSheet(c:String,t:List<GeneralReportTransactionRow>,start:Long?,end:Long?):String{val rows=mutableListOf<String>();var n=1;rows+=row(n++,listOf(cell("التقرير التفصيلي للعمليات",1)));rows+=row(n++,listOf(cell("العملة: ${currencyName(c)}",2),cell("الفترة: ${range(start,end)}",2),cell("إصدار: ${date(System.currentTimeMillis())}",2)));val h=n;rows+=row(n++,listOf(cell("التاريخ",2),cell("الشخص",2),cell("البيان",2),cell("عليه",3),cell("له",4),cell("الرصيد",2)));t.forEach{x->rows+=row(n++,listOf(cell(date(x.transactionDate)),cell(x.personName),cell(x.description.ifBlank{"—"}),if(x.type=="RECEIVABLE")number(x.amountMinor,5) else cell("—"),if(x.type=="PAYABLE")number(-x.amountMinor,6) else cell("—"),cell("—")))};if(t.isEmpty())rows+=row(n++,listOf(cell("لا توجد عمليات.")));return sheet(rows,"A$h:F${n-1}","16,28,42,18,18,20")}
    private fun summarySheet(c:String,r:List<PersonCurrencySummaryRow>,start:Long?,end:Long?):String{val rows=mutableListOf<String>();var n=1;rows+=row(n++,listOf(cell("ملخص تقرير الأشخاص",1)));rows+=row(n++,listOf(cell("العملة: ${currencyName(c)}",2),cell("الفترة: ${range(start,end)}",2),cell("إصدار: ${date(System.currentTimeMillis())}",2)));val h=n;rows+=row(n++,listOf(cell("الشخص",2),cell("العملة",2),cell("عليه",3),cell("له",4),cell("الرصيد",2),cell("أول عملية",2),cell("آخر عملية",2)));r.forEach{x->rows+=row(n++,listOf(cell(x.personName),cell(currencyName(x.currencyCode)),number(x.totalReceivableMinor,5),number(-x.totalPayableMinor,6),number(x.balanceMinor,7),cell(firstDate(x)),cell(lastDate(x))))};if(r.isEmpty())rows+=row(n++,listOf(cell("لا توجد بيانات.")));return sheet(rows,"A$h:G${n-1}","28,18,18,18,20,18,18")}
    private fun sheet(rows:List<String>,filter:String,widths:String):String{val cols=widths.split(',').mapIndexed{i,w->"<col min=\"${i+1}\" max=\"${i+1}\" width=\"$w\" customWidth=\"1\"/>"}.joinToString("");return """<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" rightToLeft="1"/></sheetViews><sheetFormatPr defaultRowHeight="20"/><cols>$cols</cols><sheetData>${rows.joinToString("")}</sheetData><autoFilter ref="$filter"/></worksheet>"""}
    private fun row(n:Int,cells:List<String>)="<row r=\"$n\">${cells.joinToString("")}</row>"
    private fun cell(v:String,style:Int=0)="<c t=\"inlineStr\" s=\"$style\"><is><t xml:space=\"preserve\">${escape(v)}</t></is></c>"
    private fun number(v:Long,style:Int)="<c t=\"n\" s=\"$style\"><v>${BigDecimal(v).movePointLeft(2).toPlainString()}</v></c>"
    private fun integer(v:Long,style:Int)="<c t=\"n\" s=\"$style\"><v>$v</v></c>"
    private fun currencyName(c:String)=when(c){"YER"->"الريال اليمني";"SAR"->"الريال السعودي";"USD"->"الدولار الأمريكي";else->c}
    private fun date(v:Long)=SimpleDateFormat("dd/MM/yyyy",Locale("ar")).format(Date(v))
    private fun range(s:Long?,e:Long?)=if(s==null&&e==null)"كل الحساب" else "${s?.let(::date)?:"غير محدد"} - ${e?.let{date(it-1)}?:"غير محدد"}"
    private fun firstDate(r:PersonCurrencySummaryRow)=listOfNotNull(r.firstReceivableDate,r.firstPayableDate).minOrNull()?.let(::date)?:"—"
    private fun lastDate(r:PersonCurrencySummaryRow)=listOfNotNull(r.lastReceivableDate,r.lastPayableDate).maxOrNull()?.let(::date)?:"—"
    private fun safe(v:String)=v.replace(Regex("[^\u0600-\u06FFA-Za-z0-9_-]+"),"_").take(50)
    private fun escape(v:String)=v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&apos;").filter{it=='\n'||it=='\r'||it=='\t'||it>=' '}
    private const val XLSX_MIME_TYPE="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
}
